image: feeni/node-chrome:latest

clone:
  depth: full              # SonarQube scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarQube artifacts will speed up your build
  steps:
    - step: &build-test-sonarqube
        name: Build, test and analyze on SonarQube
        max-time: 5
        caches:
          - node
          - sonar
        script:
          - npm install --quiet
          - npm run test -- --code-coverage --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox  
          - pipe: sonarsource/sonarqube-scan:1.0.0
            variables:
              SONAR_HOST_URL: https://michal.eu.ngrok.io/
              SONAR_TOKEN: ${SONAR_TOKEN}
              EXTRA_ARGS: '-Dsonar.sources=src -Dsonar.tests=src -Dsonar.test.inclusions="**/testing/**,**/*.spec.ts" -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info'
          - pipe: sonarsource/sonarqube-quality-gate:1.0.0
            variables:
              SONAR_TOKEN: ${SONAR_TOKEN}
          - echo "finished!"
pipelines:
  default:
    - step: *build-test-sonarqube
  pull-requests:
    '**':
      - step: *build-test-sonarqube
